spring:
  config:
    import: optional:not-secret-application.yml
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${POSTGRESDB_URL}
    username: ${POSTGRESDB_TEST_USER}
    password: ${POSTGRESDB_TEST_PASS}

exchangerate-api:
  apikey: ${EXCHANGERATEAPI_APIKEY}
  convert-endpoint: https://v6.exchangerate-api.com/v6/${exchangerate-api.apikey}/pair/